# Generated by Django 2.2.5 on 2022-01-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20220112_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='instant_book',
            field=models.BooleanField(default=False),
        ),
    ]
